# This is a basic workflow to help you get started with Actions
name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out origin/main repository under $GITHUB_WORKSPACE, so your job can access it
      - name: fetch main branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: yarn
        run: yarn

      - name: lint
        run: yarn lint

      # - name: test
      #   run: yarn test

      - name: semantic-release
        run: yarn semantic-release
        env:
          CI: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
